### ISSUE TITLE
NY Times incorrect information

### ISSUE THREAD

**Issue by hueniverse** [iamcal/oembed#154]
1. The scheme link is wrong. There should be no scheme link.
2. The url is wrong, it is missing the `/{format}/` at the end.

Also related:
1. The NY Times endpoint fails to honor maxwidth and maxheight.

**Comment by iamcal** [comment]
patches welcome, otherwise i'll get around it it eventually

**Comment by neilsmind** [comment]
@hueniverse I don't mind doing up a quick pull request. Is there a documentation link from NY Times for their oembed service? Just want to make sure I fully capture.

**Comment by hueniverse** [comment]
I don't recall anymore. I fixed it in my local copy in hueniverse/metaphor.

**Comment by robbiet480** [comment]
Fixed in #216
