### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Garito** [iamcal/oembed#160]
Hi!
Could someone explain me why this call is interpreted as a 415?
https://www.app.timefounder.com/oembed?maxwidth=1300&maxheight=1300&radius=100&APIkey=uxgtXmuOAHhNyJB8ge0vGAF5yr5tfjjrxHGr&url=https%3A%2F%2Fwww.app.timefounder.com%2Fprojects%2FmainChartWidget

Thanks!

**Comment by iamcal** [comment]
this repo is for the oembed spec and a directory of providers. for support from a particular oembed provider, please contact them directly
