### ISSUE TITLE
Two entries for "Codepen". One looks incorrect.

### ISSUE THREAD

**Issue by mchurchward** [iamcal/oembed#171]
You currently have two entries for "Codepen":
{
        "provider_name": "Codepen",
        "provider_url": "https:\/\/mybeweeg.com",
        "endpoints": [
            {
                "schemes": [
                    "https:\/\/mybeweeg.com\/w\/*"
                ],
                "url": "https:\/\/mybeweeg.com\/services\/oembed"
            }
        ]
    },
    {
        "provider_name": "Codepen",
        "provider_url": "https:\/\/codepen.io",
        "endpoints": [
            {
                "schemes": [
                    "http:\/\/codepen.io\/*",
                    "https:\/\/codepen.io\/*"
                ],
                "url": "http:\/\/codepen.io\/api\/oembed"
            }
        ]
    },

I'm pretty sure the first one is incorrect.

**Comment by iamcal** [comment]
good catch. looks like the `provider_name` is just a typo. fixed in 439af74
