### ISSUE TITLE
Update GIPHY example

### ISSUE THREAD

**Issue by 7studio** [iamcal/oembed#224]
Hi Cal,

Thank you for your work on this document. 

I would like to propose one change concerning the GIPHY example. As the API endpoint accepts three types of URL:

1.  site: [https://giphy.com/gifs/cant-hardly-wait-kW8mnYSNkUYKc](https://giphy.com/services/oembed?url=https://giphy.com/gifs/cant-hardly-wait-kW8mnYSNkUYKc)
2. short: [http://gph.is/29tcRs7](https://giphy.com/services/oembed?url=http://gph.is/29tcRs7)
3. GIF: [https://media.giphy.com/media/kW8mnYSNkUYKc/giphy.gif](https://giphy.com/services/oembed?url=https://media.giphy.com/media/kW8mnYSNkUYKc/giphy.gif)

IMHO it will be better to use the first one in the example than the link to the GIF image itself in the doc like for other providers.

I hope you will consider this change.

**Comment by iamcal** [comment]
if you submit this as a pull request i'll merge it 👍

**Comment by 7studio** [comment]
Cheers, Cal.
