### ISSUE TITLE
Add Instagram schemes to support www.

### ISSUE THREAD

**Issue by kurtfunai** [iamcal/oembed#232]
Looking at https://github.com/iamcal/oembed/blob/master/providers/instagram.yml it appears that Instagram schemes are missing support for `www.`. This may be new, but it appears that Instagram now uses `www.` for canonical URLs.

ex: https://instagram.com/p/BUHouXdgTWv -> https://www.instagram.com/p/BUHouXdgTWv

This can cause some downstream affects on users copy/pasting urls from Instagram to share links.

Would it be possible to add support for `www.` here as well?

**Comment by iamcal** [comment]
pull request welcome - provider specs are submitted by providers (or users of that provider)

**Comment by kurtfunai** [comment]
@iamcal thanks I'll try to get around to this soon :)
