### ISSUE TITLE
Youtube identifiers that start with a hyphen do not work

### ISSUE THREAD

**Issue by bemyhre** [iamcal/oembed#329]
The following is a URL:

https://www.youtube.com/watch?v=-1jd28_NKco

If you try to embed it in Wordpress OR use the Youtube example from oembed.com (changing out the id)

`https://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3D-1jd28_NKco&format=json`

it does not embed (displays as text) or in the url case, it does not return the expected json.

**Comment by bemyhre** [comment]
leading hyphen?

**Comment by nextgenthemes** [comment]
This is weird. You should put this up to YouTube itself as its their oEmbed API that strokes on this. This had nothing to do with this Rope. Maybe a short term bug that generated a ID with a leading hyphen, never seen that b4.

**Comment by raae** [comment]
Just tested this and it works, so it can probably be closed @iamcal.
