### ISSUE TITLE
Wistia Provider name appears to be incorrect

### ISSUE THREAD

**Issue by smthomas** [iamcal/oembed#350]
Wistia is listed in the providers list as `Wistia` however, when looking at the Wistia documentation, they return `Wistia, Inc`.

From the wistia.yml file:
```
- provider_name: Wistia
  provider_url: https://wistia.com/
  endpoints:
```

From the Wistia oembed documentation (https://wistia.com/support/developers/oembed) you will notice, they return:
```
{
  ...
  "provider_name":"Wistia, Inc.",
  "provider_url":"https://wistia.com",
  ...
}
```

Is the correct course of action to update the Wistia provider to fix the discrepancy?

**Comment by iamcal** [comment]
i'm not sure it matters if they are different, but i'll happily merge a PR to keep them in sync

**Comment by smthomas** [comment]
Created PR as requested #353
