### ISSUE TITLE
Add support for PeerTube video links

### ISSUE THREAD

**Issue by Zig-03** [iamcal/oembed#369]
[Peertube is a decentralized](https://joinpeertube.org/en/) video hosting project. Everyone can make a new instance based on PeerTube's source code. Would be great if we could support all peertube links of all peertube [instances](https://instances.joinpeertube.org/instances). PeerTube's [F.A.Q. page](https://joinpeertube.org/en/faq). Thank you

May be related:
https://github.com/Chocobozzz/PeerTube/issues/94
https://github.com/dessalines/lemmy/issues/156

**Comment by iamcal** [comment]
you can submit changes via a pull request

**Comment by lboklin** [comment]
The whole point of issues is to track things to solve. Closing an issue with a vacuous truth like "you can submit changes via a pull request" is very strange. How am I supposed to subscribe to a non-existing PR if I want to follow progress?
