### ISSUE TITLE
Is YouTube serving incorrect iframe code?

### ISSUE THREAD

**Issue by parris** [iamcal/oembed#408]
When I first implemented the oembed protocol on my own product I followed YouTube as an example. However, when I submitted my app to Embeddly as a provider they informed me that I had in fact not correctly implemented the protocol. When looking at more and more examples I realized that YouTube's oembed implementation likely has a bug where they've encoded things incorrectly

Here's an example youtube link: https://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiwGFalTRHDA

Here's a valid use of the protocol: https://www.ted.com/services/v1/oembed.json?url=https%3A%2F%2Fwww.ted.com%2Ftalks%2Fjill_bolte_taylor_s_powerful_stroke_of_insight

Notice that opening and closing carrots in the 2 examples differ. As it stands I need to manually fix youtube embeds on my site. I imagine everyone else needs to do the same. I think this gives a bad example for anyone following: https://oembed.com/. YouTube is listed as a primary example on the site and if people are spending time trying to double encode their HTML only to get rejected as a provider, that's no bueno - note it can be quite painful to double encode in this way.

My recommendation is to use another site as an example early on in the document and then continue to list it down below. I submitted a bug report to youtube, but I'm unsure if it would get addressed and when. Meanwhile, I'll continue to double decode. If there is a good reason that this iframe code is double encoded please let me know. If I'm wrong here maybe embeddly needs to advise providers differently and maybe other embed providers are incorrectly implementing oembed.

**Comment by iamcal** [comment]
I think you're wrong, if you're talking about the HTML fragment. Any correct JSON implementation will parse `"\u003c"` and `"<"` as being identical.

**Comment by parris** [comment]
Yea, I am talking about the HTML fragment. A little further clarification about why I think this might be an issue:

When an endpoint returns a JSON string that contains `\u003c` a browser will render it as `<`. In this case, it doesn't do that, which means it's escaped. 

This can be OK if you're just directly rendering the string and putting it within another blob of markup for the browser to render. If you're instead processing the HTML in some way it will get recognized as plain text instead of an HTML fragment.

**Comment by iamcal** [comment]
It is returning valid JSON. This has nothing to do with viewing it in a browser or not. It is a correct and valid way of encoding an opening brace in a JSON string.
