### ISSUE TITLE
Flickr oembed returns "html" property in lower case when it's case sensitive

### ISSUE THREAD

**Issue by notken** [iamcal/oembed#409]
I'm not sure if I should be reporting this here or directly with flickr, but I'm having a problem testing oembed with flickr.

My test account name has a capital N, but when I use oembed the html it sends back changes the account name to have a lower case n. But it looks like flickr's system is case-sensitive, because it results in a 404 unless I change it to N.

Example:
https://www.flickr.com/services/oembed/?format=json&url=https://www.flickr.com/photos/49264659@N06/albums/72157653413644381

returns

{"type":"rich","flickr_type":"album","title":"Arsenal v West Brom","author_name":"gamespress","author_url":"https:\/\/www.flickr.com\/photos\/49264659@N06\/","width":1024,"height":683,"web_page":"https:\/\/www.flickr.com\/photos\/49264659@n06\/albums\/72157653413644381","thumbnail_url":"https:\/\/live.staticflickr.com\/7657\/17452207044_9960dd9179_b.jpg","thumbnail_width":1024,"thumbnail_height":683,"web_page_short_url":"https:\/\/flic.kr\/s\/aHskcrTvt4","html":"<a data-flickr-embed=\"true\" href=\"https:\/\/www.flickr.com\/photos\/49264659@n06\/albums\/72157653413644381\" title=\"Arsenal v West Brom by gamespress, on Flickr\"><img src=\"https:\/\/live.staticflickr.com\/7657\/17452207044_9960dd9179_b.jpg\" width=\"1024\" height=\"683\" alt=\"IMG_2128\"><\/a><script async src=\"https:\/\/embedr.flickr.com\/assets\/client-code.js\" charset=\"utf-8\"><\/script>","version":"1.0","cache_age":3600,"provider_name":"Flickr","provider_url":"https:\/\/www.flickr.com\/"}

Notice that 49264659@N06 has been changed to 49264659@n06, resulting in a 404.

**Comment by iamcal** [comment]
This is a bug on Flickr's side - you should report it to them 👍
