### ISSUE TITLE
List of providers in some programatically format

### ISSUE THREAD

**Issue by rafaelmartins** [iamcal/oembed#45]
Hello,

while I really like the oEmbed spec, I miss a centralized list of providers I can rely on. Auto discovering providers is pretty cool, but not all the providers are allowing it, and it is quite hard for webapps that rely heavily on ajax, like rdio.com.

I did some effort on getting such list in JSON scrapping oembed.com, but several providers seems to be outdated or with wrong schemes:

https://github.com/rafaelmartins/oembed-providers

what about adding a list like this one to oembed.com, even if manually maintained, so people who adds new providers can fix the list too, and keep it up2date?

**Comment by iamcal** [comment]
this is now generated from the same data source that the web page uses: http://oembed.com/providers.json
