### ISSUE TITLE
oembed.com/provider.json caches not invalidated

### ISSUE THREAD

**Issue by jbertoen** [iamcal/oembed#501]
The caches should be flushed following the closed issue below:

once all caches empty (should be in the next 10 mins) then it should be functional everywhere

_Originally posted by @iamcal in https://github.com/iamcal/oembed/issues/499#issuecomment-737638701_

But it still gives the same error:
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function yaml_parse_file() in /var/www/html/oembed.com/www/json.php:14
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/oembed.com/www/json.php</b> on line <b>14</b><br />

Seems to be some invalidation issue at cloudfront.

**Comment by jbertoen** [comment]
age: 48348
content-encoding: gzip
content-length: 184
content-type: text/plain; charset=utf-8
date: Thu, 03 Dec 2020 01:30:09 GMT
server: Apache
status: 200
vary: Accept-Encoding
via: 1.1 ff991951152c9edc076607bc5a471613.cloudfront.net (CloudFront)
x-amz-cf-id: AHrRDif_Z_tQ0BUOGUldcBCLwVYJucc3Qgd8eDwMUFootoj4_EEZhg==
x-amz-cf-pop: AMS50-C1
x-cache: Hit from cloudfront

**Comment by iamcal** [comment]
i've explicitly invalidate the cache now - the cache age was longer than i though
