### ISSUE TITLE
Refresh Oauth 2.0 tokens failed

### ISSUE THREAD

**Issue by gogapi70** [iamcal/oembed#580]
Dear experts,

while using **oa2c_grant** tcode in sap ,status code is red how to solve this.
![oa2c_grant](https://user-images.githubusercontent.com/90900254/134766869-7ae47b90-70c3-4b15-b101-16f3341245c0.PNG)
s.

**Comment by iamcal** [comment]
this repo is for the OEmbed spec, not OAuth

**Comment by gogapi70** [comment]
Sir how to solve this problem? i am stuck at last moment.
