### ISSUE TITLE
Support x.com URLs for Twitter/X

### ISSUE THREAD

**Issue by glen-84** [iamcal/oembed#710]
When you click "Copy link", you now get an x.com URL, f.e.:

https://x.com/PicturesFoIder/status/1701986685829947462?s=20

This host name should probably also be supported for Twitter.

**Comment by Forgetmenot1** [comment]
How do you recover deleted content/videos off of a page on twitter/ x
https://twitter.com/ohtopdude/status/1480029185578049536?s=21…
https://twitter.com/ohtopdude/status/1483131182170660868…
How do you recover deleted status videos 📹 😪 PLEASE 🙏  this is adult content of me and I need to get ahold of them for an ease of mind fuckery 
![Screenshot_20240920_123916_Edge](https://github.com/user-attachments/assets/c36a0bd9-a136-4dd0-83b9-a33137ccdfc2)
