### ISSUE TITLE
YouTube Live share scheme missing

### ISSUE THREAD

**Issue by GilNovacomm** [iamcal/oembed#770]
## Issue:
Youtube saves the live streaming sessions on a /live path.
![image](https://github.com/user-attachments/assets/7d3721e5-4695-40d4-ad5e-3ed64cfdf834)

### Current scheme:

```javascript
  - schemes:
    - https://*.youtube.com/watch*
    - https://*.youtube.com/v/*
    - https://youtu.be/*
    - https://*.youtube.com/playlist?list=*
    - https://youtube.com/playlist?list=*
    - https://*.youtube.com/shorts*
    - https://youtube.com/shorts*
    - https://*.youtube.com/embed/*
```
## Background:
I'm coming from Drupal where this causes the error "No matching provider found." since there are no endpoint/scheme hits.

## Solution:
Add pattern to scheme list

```javascript
    - https://*.youtube.com/live*
    - https://youtube.com/live*
```

MR: https://github.com/iamcal/oembed/pull/771

**Comment by GilNovacomm** [comment]
I have created a MR:
https://github.com/iamcal/oembed/pull/771

**Comment by iamcal** [comment]
merged, thanks
