### ISSUE TITLE
Providers must specify one or more URL scheme and API endpoint pairs.

### ISSUE THREAD

**Issue by zldrq** [iamcal/oembed#78]
specify WHERE, i wonder

**Comment by rerraw** [comment]
Hi
How i can add Oembed Soundcloud to my Wordpress Widgets?
I added this Oembed Soundcloud Link within my widget but don't show the Sound Player

echo '<a rel="alternate" type="application/'.$YPE_sc_oembedtype.'" href="'.$YPE_sc_url.'&format='.$YPE_sc_format.'&maxwidth='.$YPE_sc_maxwidth.'&maxheight='.$YPE_sc_maxheight.'&color='.$YPE_sc_modify_color.'&auto_play='.$YPE_sc_autoplay.'&show_comments='.$YPE_sc_showcomments.'&iframe='.$YPE_sc_iframe.'"></a>';

**Comment by iamcal** [comment]
this repo is not for oembed or wordpress support, sorry.
